# Config
# :PROPERTIES:
# :header-args: :tangle ../config/xinitrc :comments org
# :END:

# My workflow includes launching Emacs under X11[fn:1] without the use of a display manager, controlling everything within Emacs, while still providing the functionality of a desktop environment.


compton &
xss-lock -- slock &
exec dbus-launch --exit-with-session emacs -mm --debug-init
